FROM python:3.12-slim

# Environment variable: Don't write .pyc files(__pycache__)
ENV PYTHONDONTWRITEBYTECODE=1

# Environment variable: Enable output buffering (set to 1 for stdout to show immediately)
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit","run","streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]