FROM python:3.10-slim-buster

# Environment variable: Don't write .pyc files(__pycache__)
ENV PYTHONDONTWRITEBYTECODE=1

# Environment variable: Enable output buffering (set to 1 for stdout to show immediately)
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy BOTH backend code and src/
# copies your FastAPI code
# copies your src package too
COPY ./backend/ .      
COPY ./src/ ./src/     
COPY .project-root . 
COPY ./config/ ./config/



RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
